name: Sync Advanced Classic Editor

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '20 12 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name 'Farhad Sakhaei'
          git config --global user.email 'farhad0@gmail.com'

      - name: Configure Git
        run: |
          git checkout master

      - name: Remove unwanted files
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name '.github' ! -name '.git' -exec rm -rf {} +
          git commit -am "Remove all files and folders except .svn, .github, and .git"
          git push origin master

      - name: Get plugin from SVN
        run: |
          svn checkout https://plugins.svn.wordpress.org/best-editor/trunk .
          rm -rf ".svn"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Sync plugin from SVN"
          git push origin master
