name: Sync Advanced Classic Editor
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Clean unwanted files
        run: |
          find . -type f ! -path './.svn/*' ! -path './.github/*' -exec rm -f {} +

      - name: Configure Git
        run: |
          git config --global user.name 'Farhad Sakhaei'
          git config --global user.email 'farhad0@gmail.com'

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Sync from WordPress.org SVN trunk"
          git push
