name: Sync Advanced Classic Editor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Clean up current files (except .svn and .github folders)
        run: |
          find . -type f -not -path './.svn/*' -not -path './.github/*' -exec rm -f {} +
          find . -type d -not -path './.svn' -not -path './.github' -not -path '.' -not -path '..' -exec rm -rf {} +

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync from SVN trunk
        run: |
          svn export --force https://plugins.svn.wordpress.org/best-editor/trunk .

      - name: Configure Git
        run: |
          git config --global user.name 'Farhad Sakhaei'
          git config --global user.email 'farhad0@gmail.com'

      - name: Commit and push changes
        run: |
          git add -A
          git commit -m "Sync from WordPress.org SVN trunk"
          git push
