name: Sync Advanced Classic Editor

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name 'Farhad Sakhaei'
          git config --global user.email 'farhad0@gmail.com'

      - name: Configure Git
        run: |
          git checkout master

      - name: Remove unwanted files
        run: |
          find . -type f -not -path "*.github*" -delete
          git commit -m "Remove all files and folders except .svn, .github, and .git"
          git push origin master

      - name: Get plugin from SVN
        run: svn checkout https://plugins.svn.wordpress.org/best-editor/trunk .

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Sync plugin from SVN"
          git push origin master
