name: Clean Master Branch

on:
  push:
    branches: [ master ]

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name 'Farhad Sakhaei'
          git config --global user.email 'farhad0@gmail.com'
      - name: Remove unwanted files
        run: |
          git rm -r .
          git reset -- .svn .github .git
          git commit -m "Remove all files and folders except .svn, .github, and .git"

