name: Sync Advanced Classic Editor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Subversion
        run: sudo apt-get update && sudo apt-get install -y subversion

      - name: Configure Git
        run: |
          git checkout master
          git config --global user.name 'Farhad Sakhaei'
          git config --global user.email 'farhad0@gmail.com'

      - name: Configure Git
        run: |
          git checkout master
          git config --global user.name 'Farhad Sakhaei'
          git config --global user.email 'farhad0@gmail.com'
      - name: Remove unwanted files
        run: |
          git rm -r .
          git reset -- .svn .github .git
          git commit -m "Remove all files and folders except .svn, .github, and .git"
          git push origin master

      - name: Get plugin from SVN
        run: svn checkout https://plugins.svn.wordpress.org/best-editor/trunk .

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Sync plugin from SVN revision [svn log -r HEAD --xml | xpath //revision/@number]"

      - name: Push changes to GitHub
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to fetch tags for pushing
